version: '3.8'

services:
  health-monitor:
    build: .
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - TABLE_NAME=${TABLE_NAME}
      - ENVIRONMENT=${ENVIRONMENT}